// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ITEXPContext))]
    [Migration("20221211153206_AddClientAndContactTable")]
    partial class AddClientAndContactTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Mikle"
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "John"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClientContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientContact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            ContactType = "SIM",
                            ContactValue = "12345"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            ContactType = "SIM",
                            ContactValue = "54321"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            ContactType = "SIM2",
                            ContactValue = "33333"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 2,
                            ContactType = "SIM",
                            ContactValue = "756567"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 2,
                            ContactType = "SIM2",
                            ContactValue = "872364"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "2-3шт.",
                            TodoId = new Guid("e46a7742-3d81-4ea0-b371-8bb5f37f2384")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Header", "Category")
                        .IsUnique();

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e46a7742-3d81-4ea0-b371-8bb5f37f2384"),
                            Category = (byte)3,
                            Color = "Red",
                            CreatedOn = new DateTime(2022, 12, 11, 15, 32, 5, 952, DateTimeKind.Utc).AddTicks(2686),
                            Header = "Create a ticket",
                            Status = (byte)0
                        },
                        new
                        {
                            Id = new Guid("2c582e26-1773-47a8-8c82-da754dd30639"),
                            Category = (byte)1,
                            Color = "Green",
                            CreatedOn = new DateTime(2022, 12, 11, 15, 32, 5, 952, DateTimeKind.Utc).AddTicks(2689),
                            Header = "Request information",
                            Status = (byte)0
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClientContact", b =>
                {
                    b.HasOne("Domain.Entities.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.HasOne("Domain.Entities.Todo", "Todo")
                        .WithMany("Comments")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Domain.Entities.Todo", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
