// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ITEXPContext))]
    [Migration("20221211111908_CreateIndex")]
    partial class CreateIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "2-3шт.",
                            TodoId = new Guid("fa8aaa37-b319-471d-ad54-43757cc41863")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Header", "Category")
                        .IsUnique();

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa8aaa37-b319-471d-ad54-43757cc41863"),
                            Category = (byte)3,
                            Color = "Red",
                            CreatedOn = new DateTime(2022, 12, 11, 11, 19, 8, 50, DateTimeKind.Utc).AddTicks(6920),
                            Header = "Create a ticket",
                            Status = (byte)0
                        },
                        new
                        {
                            Id = new Guid("f9d74be7-0cd1-4a66-8dbd-31ae952300a9"),
                            Category = (byte)1,
                            Color = "Green",
                            CreatedOn = new DateTime(2022, 12, 11, 11, 19, 8, 50, DateTimeKind.Utc).AddTicks(6931),
                            Header = "Request information",
                            Status = (byte)0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.HasOne("Domain.Entities.Todo", "Todo")
                        .WithMany("Comments")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Domain.Entities.Todo", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
